In [2]:
import pandas as pd

df=pd.read_csv('SMSSpamCollection.csv',header=None,error_bad_lines=False)

df.head()

b'Skipping line 2: expected 2 fields, saw 3\nSkipping line 6: expected 2 fields, saw 3\nSkipping line 7: expected 2 fields, saw 3\nSkipping line 12: expected 2 fields, saw 3\nSkipping line 13: expected 2 fields, saw 5\nSkipping line 14: expected 2 fields, saw 3\nSkipping line 17: expected 2 fields, saw 3\nSkipping line 21: expected 2 fields, saw 3\nSkipping line 30: expected 2 fields, saw 3\nSkipping line 32: expected 2 fields, saw 3\nSkipping line 38: expected 2 fields, saw 3\nSkipping line 43: expected 2 fields, saw 4\nSkipping line 49: expected 2 fields, saw 3\nSkipping line 50: expected 2 fields, saw 3\nSkipping line 53: expected 2 fields, saw 3\nSkipping line 55: expected 2 fields, saw 3\nSkipping line 58: expected 2 fields, saw 5\nSkipping line 59: expected 2 fields, saw 3\nSkipping line 65: expected 2 fields, saw 3\nSkipping line 67: expected 2 fields, saw 4\nSkipping line 69: expected 2 fields, saw 4\nSkipping line 82: expected 2 fields, saw 3\nSkipping line 87: expected 2 fiel

0                                                  1
0  label                                               text
1    0.0                      Ok lar... Joking wif u oni...
2    1.0  Free entry in 2 a wkly comp to win FA Cup fina...
3    0.0  U dun say so early hor... U c already then say...
4    0.0  Even my brother is not like to speak with me. ...

In [5]:
df.rename(columns = {0:'Label'}, inplace = True) 
df.rename(columns = {1:'Text'}, inplace = True) #rename column names

df=df.drop(df.index[0])
df

Label                                               Text
2      1.0  Free entry in 2 a wkly comp to win FA Cup fina...
3      0.0  U dun say so early hor... U c already then say...
4      0.0  Even my brother is not like to speak with me. ...
5      0.0  As per your request Melle Melle Oru Minnaminun...
6      1.0  WINNER As a valued network customer you have b...
...    ...                                                ...
4248   0.0  Why dont you wait til at least wednesday to se...
4249   0.0                                       Huh y lei...
4250   0.0                 Will  b going to esplanade fr home
4251   0.0  The guy did some bitching but I acted like id ...
4252   0.0                         Rofl. Its true to its name

[4251 rows x 2 columns]

In [6]:
df=df.dropna()

In [7]:

X=df.drop('Label',axis=1)

In [8]:

## Get the Dependent features
y=df['Label']

In [9]:
X.shape

(4251, 1)

In [10]:
y.shape

(4251,)

In [11]:

import tensorflow as tf

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\user\appdata\

In [12]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
#we need to add 0 in front or back to make sentence equal in len
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense


In [13]:

### Vocabulary size any number
voc_size=5000

In [14]:
messages=X.copy()

In [16]:
messages['Text']

2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Even my brother is not like to speak with me. ...
5       As per your request Melle Melle Oru Minnaminun...
6       WINNER As a valued network customer you have b...
                              ...                        
4248    Why dont you wait til at least wednesday to se...
4249                                         Huh y lei...
4250                   Will  b going to esplanade fr home
4251    The guy did some bitching but I acted like id ...
4252                           Rofl. Its true to its name
Name: Text, Length: 4251, dtype: object

In [17]:
messages.reset_index(inplace=True)

In [18]:
import nltk
import re
from nltk.corpus import stopwords

In [19]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [20]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['Text'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    #if word in review not in stop wordsthen only stem itand put back to review
    review = ' '.join(review)
    #then join the words in review
    corpus.append(review)
    #and form sentences

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062


3525
3526
3527
3528
3529
3530
3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724


In [17]:
corpus

['say anni list polit group support third trimest abort demand',
 'declin coal start start natur ga took start begin presid georg w bush administr',
 'hillari clinton agre john mccain vote give georg bush benefit doubt iran',
 'health care reform legisl like mandat free sex chang surgeri',
 'econom turnaround start end term',
 'chicago bear start quarterback last year total number tenur uw faculti fire last two decad',
 'jim dunnam live district repres year',
 'person stage work activ last year pass along russ feingold toughest ethic reform sinc waterg',
 'howev took million oregon lotteri fund port newport eventu land new noaa marin oper center pacif',
 'say gop primari oppon glenn grothman joe leibham cast compromis vote cost million higher electr cost',
 'first time histori share nation popular vote margin smaller latino vote margin',
 'sinc nearli million american slip middl class poverti',
 'mitt romney governor massachusett didnt slow rate growth govern actual cut',
 'economi ble

In [21]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]

In [22]:
onehot_repr
#each word in a sentence is represented as index out of 5000

[[1969,
  3670,
  1932,
  4148,
  723,
  2855,
  2799,
  4915,
  2132,
  4314,
  3837,
  4849,
  2855,
  4664,
  3670,
  4143,
  1939,
  1841,
  4750],
 [2751, 3498, 1123, 891, 2694, 2751, 2439, 224, 1123],
 [4499, 2779, 3298, 396, 1356, 3298, 1720, 354],
 [1283,
  4943,
  703,
  703,
  2471,
  3579,
  29,
  2958,
  4233,
  4184,
  578,
  4159,
  3422,
  661,
  4184],
 [3352,
  1885,
  73,
  3007,
  2916,
  1540,
  3990,
  2114,
  2684,
  4998,
  2684,
  4355,
  17,
  4859,
  1852],
 [552,
  2908,
  2751,
  4667,
  2309,
  1185,
  348,
  424,
  552,
  722,
  1969,
  4998,
  552,
  1185,
  2375,
  1969],
 [4824,
  2332,
  2871,
  664,
  4402,
  1678,
  4429,
  4293,
  419,
  1621,
  1783,
  976,
  4429,
  2465,
  100,
  361],
 [960, 4966],
 [3384, 4006, 2290, 1402],
 [3724, 2751, 1911, 2580, 442, 3440, 4726, 4088, 4966, 4726, 4359],
 [3165, 3619, 2914, 2751, 4038, 3619, 2914, 3205, 2831],
 [1204, 2580, 442],
 [2290, 820, 417, 2908, 2809, 2809, 1102],
 [371, 4377, 563, 3278, 3510, 3209],

In [23]:
#before giving to embedding layer make all sentences of equal len
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)#post=add at end
print(embedded_docs)

[[   0 1969 3670 ... 1939 1841 4750]
 [   0    0    0 ... 2439  224 1123]
 [   0    0    0 ... 3298 1720  354]
 ...
 [   0    0    0 ... 2475 2502 3509]
 [   0    0    0 ... 2890 4732 1969]
 [   0    0    0 ... 4176 2994  442]]


In [24]:
embedded_docs[0]

array([   0, 1969, 3670, 1932, 4148,  723, 2855, 2799, 4915, 2132, 4314,
       3837, 4849, 2855, 4664, 3670, 4143, 1939, 1841, 4750])

In [25]:
## Creating model
embedding_vector_features=40 #any
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))#sentlen=20
#output of embedding layer is given to lstm layer
model.add(LSTM(100))#one lstm with 100 neuron
model.add(Dense(1,activation='sigmoid'))#classification prob
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

W0116 23:05:07.582766 24264 deprecation.py:506] From c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\keras\initializers.py:119: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0116 23:05:07.611007 24264 deprecation.py:506] From c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0116 23:05:07.892340 24264 deprecation.py:323] From c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\nn_impl.py:18

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [26]:
len(embedded_docs),y.shape

(4251, (4251,))

In [27]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [28]:

X_final.shape,y_final.shape

((4251, 20), (4251,))

In [29]:
X_final

array([[   0, 1969, 3670, ..., 1939, 1841, 4750],
       [   0,    0,    0, ..., 2439,  224, 1123],
       [   0,    0,    0, ..., 3298, 1720,  354],
       ...,
       [   0,    0,    0, ..., 2475, 2502, 3509],
       [   0,    0,    0, ..., 2890, 4732, 1969],
       [   0,    0,    0, ..., 4176, 2994,  442]])

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [31]:
### Finally Training
model.fit(X_train,y_train,epochs=10,batch_size=64)

Epoch 1/10
2848/2848 [==============================] - 1s 507us/sample - loss: 0.3741 - acc: 0.8645
Epoch 2/10
2848/2848 [==============================] - 1s 352us/sample - loss: 0.1379 - acc: 0.9624
Epoch 3/10
2848/2848 [==============================] - 1s 326us/sample - loss: 0.0553 - acc: 0.9849
Epoch 4/10
2848/2848 [==============================] - 1s 337us/sample - loss: 0.0274 - acc: 0.9926
Epoch 5/10
2848/2848 [==============================] - 1s 333us/sample - loss: 0.0202 - acc: 0.9947
Epoch 6/10
2848/2848 [==============================] - 1s 348us/sample - loss: 0.0139 - acc: 0.9958
Epoch 7/10
2848/2848 [==============================] - 1s 342us/sample - loss: 0.0103 - acc: 0.9975
Epoch 8/10
2848/2848 [==============================] - 1s 337us/sample - loss: 0.0074 - acc: 0.9979
Epoch 9/10
2848/2848 [==============================] - 1s 342us/sample - loss: 0.0072 - acc: 0.9986
Epoch 10/10
2848/2848 [==============================] - 1s 367us/sample - loss: 0.0054 - a

In [32]:
#accuracy
y_pred=model.predict_classes(X_test)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [33]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [34]:
model.fit(X_train,y_train,epochs=10,batch_size=64)

Epoch 1/10
2848/2848 [==============================] - 2s 548us/sample - loss: 0.3772 - acc: 0.8743
Epoch 2/10
2848/2848 [==============================] - 1s 358us/sample - loss: 0.1498 - acc: 0.9561
Epoch 3/10
2848/2848 [==============================] - 1s 367us/sample - loss: 0.0661 - acc: 0.9835
Epoch 4/10
2848/2848 [==============================] - 1s 359us/sample - loss: 0.0342 - acc: 0.9919
Epoch 5/10
2848/2848 [==============================] - 1s 387us/sample - loss: 0.0239 - acc: 0.9933
Epoch 6/10
2848/2848 [==============================] - 1s 356us/sample - loss: 0.0226 - acc: 0.9933
Epoch 7/10
2848/2848 [==============================] - 1s 417us/sample - loss: 0.0137 - acc: 0.9961
Epoch 8/10
2848/2848 [==============================] - 1s 398us/sample - loss: 0.0117 - acc: 0.9965
Epoch 9/10
2848/2848 [==============================] - 1s 337us/sample - loss: 0.0094 - acc: 0.9979
Epoch 10/10
2848/2848 [==============================] - 1s 343us/sample - loss: 0.0082 - a

In [35]:
y_pred=model.predict_classes(X_test)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [44]:
y_test

array(['0.0', '0.0', '0.0', ..., '0.0', '0.0', '0.0'], dtype=object)

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(round(y_test),y_pred)

TypeError: type numpy.ndarray doesn't define __round__ method

In [37]:

from sklearn.metrics import confusion_matrix

In [38]:

confusion_matrix(y_test,y_pred)

TypeError: '<' not supported between instances of 'int' and 'str'